id: P005364
initial_creation_type: ocr
source_metadata:
  id: bdr:W25278
  title: 'མཉམ་མེད་སྟོན་པའི་རྗེས་འཇུག་རབ་ཏུ་བྱུང་བ་རྣམས་དང་འབྲེལ་བའི་ཆོས་སྣ་ཚོགས་ཀྱི་ཁུངས་བརྗོད་པ། '
  author: ''
  volumes:
    8f9ad99e729f4c85b9b6cbc67dc1ea00:
      image_group_id: I1KG10347
      title: ''
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
