id: P005364
initial_creation_type: ocr
source_metadata:
  id: bdr:W25278
  title: 'མཉམ་མེད་སྟོན་པའི་རྗེས་འཇུག་རབ་ཏུ་བྱུང་བ་རྣམས་དང་འབྲེལ་བའི་ཆོས་སྣ་ཚོགས་ཀྱི་ཁུངས་བརྗོད་པ། '
  author: ''
  volumes: {}
