id: I64DA6CCE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:03:15+00:00'
last_modified: '2022-06-08T02:33:44.465680+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25278
  title: 'མཉམ་མེད་སྟོན་པའི་རྗེས་འཇུག་རབ་ཏུ་བྱུང་བ་རྣམས་དང་འབྲེལ་བའི་ཆོས་སྣ་ཚོགས་ཀྱི་ཁུངས་བརྗོད་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    14C8:
      image_group_id: I1KG10347
      title: ''
      total_pages: 416
      order: 1
      base_file: 14C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
